FROM alpine

RUN apk update; apk add vim

CMD ["vim", "hello_world.c"]

# BUILDING: docker build ./ -t ex00
# RUNNING: docker run -it ex00
# Note: Make sure Char is running active (docker-machine ls)

# https://rominirani.com/docker-tutorial-series-writing-a-dockerfile-ce5746617cd
