FROM alpine
# base image

# Installing vim:
RUN apk update && \
	apk add vim 

# Launching vim
CMD ["vim"]

# BUILDING: 
# docker build ./ -t ex00

# RUNNING: 
# docker run -it --rm ex00

# Note: Make sure Char is running active (docker-machine ls)

# Research Links:
# https://rominirani.com/docker-tutorial-series-writing-a-dockerfile-ce5746617cd
